version: "0.2"
ignorePaths:
  - po
  - tools
  - subprojects
words:
  - accels
  - builddir
  - buildsystem
  - dbus
  - debugpy
  - DEVEL
  - FLATPAK
  - fullscreen
  - fullscreened
  - gresource
  - gsignals
  - libsecrets
  - Mojang
  - pkgconfig
  - pkgdatadir
  - PYOBJECT
  - sourceroot
